name: check-sfa

on:
  push:
    paths:
      - 'src/static_analysis/sast/src/**.py'

permissions:
  contents: read

jobs:
  check-sfa:
    container:
      image: python:3.11.3-bullseye
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: src/static_analysis/sast
    env:
      analysis_dir: src
    steps:
      - uses: actions/checkout@v3
      - name: Install Poetry and SFA dependencies
        run: |-
          curl -sSL https://install.python-poetry.org | python3 -
          export PATH="/github/home/.local/bin:$PATH"
          poetry install
      - name: Check code formatting
        run: |-
          poetry run black --check ${{env.analysis_dir}} --line-length 120 --skip-magic-trailing-comma
          poetry run isort --check ${{env.analysis_dir}} --profile black
      - name: Check typing
        run: |-
          poetry run mypy ${{env.analysis_dir}}
      - name: Check for security issues
        run: |-
          poetry run bandit --recursive ${{env.analysis_dir}}
